# Generated by Django 5.2.8 on 2025-11-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conductor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conductor'),
        ),
    ]
