# Generated by Django 5.2.8 on 2025-11-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_latitud_cliente_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa del Vehículo'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
    ]
